import IVehicleDto from '../../@interfaces/swApi/IVehicleDto';
import IVehiclesResponse from '../../@interfaces/swApi/IVehicleResponse';

export const mockVehicles: Array<IVehicleDto> = [
  {
    url: 'https://swapi.dev/api/vehicles/88/',
    name: 'TIE bomber',
    model: 'TIE/sa bomber',
    manufacturer: 'Sienar Fleet Systems',
    cost_in_credits: 'unknown',
    length: '7.8',
    max_atmosphering_speed: '850',
    crew: '1',
    passengers: '0',
    cargo_capacity: 'none',
    consumables: '2 days',
    vehicle_class: 'space/planetary bomber',
    pilots: [],
    films: ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
    created: '2014-12-15T12:33:15.838000Z',
    edited: '2014-12-20T21:30:21.675000Z',
  },
  {
    url: 'https://swapi.dev/api/vehicles/99/',
    name: 'AT-AT',
    model: 'All Terrain Armored Transport',
    manufacturer: 'Kuat Drive Yards, Imperial Department of Military Research',
    cost_in_credits: 'unknown',
    length: '20',
    max_atmosphering_speed: '60',
    crew: '5',
    passengers: '40',
    cargo_capacity: '1000',
    consumables: 'unknown',
    vehicle_class: 'assault walker',
    pilots: [],
    films: ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
    created: '2014-12-15T12:38:25.937000Z',
    edited: '2014-12-20T21:30:21.677000Z',
  },
  {
    url: 'https://swapi.dev/api/vehicles/77/',
    name: 'AT-ST',
    model: 'All Terrain Scout Transport',
    manufacturer: 'Kuat Drive Yards, Imperial Department of Military Research',
    cost_in_credits: 'unknown',
    length: '2',
    max_atmosphering_speed: '90',
    crew: '2',
    passengers: '0',
    cargo_capacity: '200',
    consumables: 'none',
    vehicle_class: 'walker',
    pilots: ['https://swapi.dev/api/people/13/'],
    films: ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
    created: '2014-12-15T12:46:42.384000Z',
    edited: '2014-12-20T21:30:21.679000Z',
  },
];

export const mockVehiclesResponse: IVehiclesResponse = {
  count: 3,
  next: 'https://swapi.dev/api/vehicles/?page=2',
  previous: null,
  results: [...mockVehicles],
};
